### ISSUE TITLE
New Mozilla.org strings

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla-l10n/www.mozilla.org#102]
https://www.mozilla.org/en-US/?v=b is already launched as main when u get to mozilla.org

There is also: https://www.mozilla.org/en-US/?v=a which I did not get it till now from the mail one. 
I looked for strings in this repo to translate them but no result.

**Comment by flodolo** [comment]
Home page testing (with variants) has been going on for several months only for en-US, there's still nothing available for localization (i.e. no winner).

Same happened for firefox/new, which recently got a winner ("Forest" design) and it's been localized.

**Comment by ioana-chiorean** [comment]
Oke. 👍 Will wait!  ⏳  Sorry for the bother!  🙇
