### ISSUE TITLE
Japanese translation for Participation guidelines

### ISSUE THREAD

**Issue by flodolo** [mozilla-l10n/www.mozilla.org#181]
I've just realized Japanese has a translation from that file, dating back to 2016
https://github.com/mozilla-l10n/www.mozilla.org/commit/f2c7907f462c9447635c7a9a28a49effe3a6a3b4

Two issues:
* This file is obsolete at this point.
* I'm not sure the Participation team is OK with an unreviewed translation to live on mozilla.org, this page is not open for translation at the moment.

@peiying2 @kyoshino

**Comment by kyoshino** [comment]
Yeah, I'm aware of that. Will complete the translation on [Pontoon](https://pontoon.mozilla.org/ja/mozillaorg/mozorg/about/governance/policies/participation.lang) hopefully by next week. 37 strings untranslated now.

**Comment by flodolo** [comment]
Please see the second point before doing any translation, we might need to remove the file.

**Comment by kyoshino** [comment]
Hmm, [this page](https://www.mozilla.org/en-US/about/governance/policies/participation/) has been open for translation for a while. I'll remove the old translation later anyway.

**Comment by flodolo** [comment]
Again, it's not open for translation. It was translated by legal council for a limited set of locales.

**Comment by kyoshino** [comment]
Really? I thought some people were encouraging the translation before SF All Hands. Anyway anyway, the file is obsolete, it's no longer displayed on the [translated page](https://www.mozilla.org/ja/about/governance/policies/participation/). Please remove the file and disable the resource on Pontoon.

**Comment by flodolo** [comment]
At this point we don't really own the decision. If the Participation team is OK with having that file translated, it will be available as an opt-in file from the dashboard. @peiying2 can you check or confirm?

As a reminder, files in the Japanese folder are only partially managed by us, since you're translating pages that are not exposed to other languages.

**Comment by kyoshino** [comment]
I've just removed the file in https://github.com/mozilla-l10n/www.mozilla.org/commit/a739f1d7dcc6af9d60d6dfc7bffdc8e233f10456

**Comment by flodolo** [comment]
OK, thanks. Let's see if Peiying can get an answer.

**Comment by peiying2** [comment]
@kyoshino I will check with Participation team on this. In addition to that it contains legal content which requires the service of a l10n agency, the team needs to fund the project. I think the latter is the main reason for it not adding more languages at this point. I will follow up with an email once I hear back from them.
