### ISSUE TITLE
WNP66 'Create a Firefox Account' button and login link

### ISSUE THREAD

**Issue by amychurchwell** [mozilla-l10n/www.mozilla.org#281]
![Screen Shot 2019-03-14 at 10 46 27 AM](https://user-images.githubusercontent.com/30483988/54379333-7076ce00-4646-11e9-9ebd-46a726f12fe1.png)
The strings:

> Create a Firefox Account
> Have an account? Log in

Were missed in the original string extraction PR and need to be added. Apologies.

**Comment by flodolo** [comment]
I completely missed the second message on Slack :-\

We have a "Create a Firefox Account" string. We don't have anything that looks like the second one, so I would strongly suggest to figure out an alternative solution.

I see a `Already have an account?` and "Sign in" in two separate strings at the moment
https://github.com/mozilla-l10n/www.mozilla.org/blob/master/en-US/firefox/accounts-2018.lang#L117-L126

Leaving this into @peiying2 hands at this point, but we need to meet halfway, given we're 3 business day from launching.

**Comment by amychurchwell** [comment]
@flodolo totally agree. Not attached to a particular phrase as long as the meaning is the same.
"Already have an account?" "Sign in" works great, I can update the page.

**Comment by flodolo** [comment]
Please wait for Peiying at this point before making changes, I'm afraid that's not a good solution either. Your design has one string with a link on the CTA, I have no clue where "Sign in" is used (maybe a button).
