### ISSUE TITLE
Unclosed anchor tag in locale/an/firefox/new/quantum.lang

### ISSUE THREAD

**Issue by pdehaan** [mozilla-l10n/www.mozilla.org#306]
https://github.com/mozilla-l10n/bedrock-l10n/blob/64ff442bb9de464ae1d86a548a0d98c134573090/an/firefox/new/quantum.lang#L140

```sh
node htmllinter.js 'locale/an/**/*.lang'
```

### locale/an/firefox/new/quantum.lang
```js
[
  {
    "column": 64,
    "code": "E042",
    "data": {},
    "rule": "tag-close",
    "file": "locale/an/firefox/new/quantum.lang",
    "html": "La tuya descargar empecipiará automaticament. No ha funcionau? <a id=\"%(id)s\" href=\"%(fallback_url)s\">Preba tornarndo-lo a descargar."
  }
]
```

**Comment by flodolo** [comment]
Fixed in Pontoon
https://pontoon.mozilla.org/an/mozillaorg/all-resources/?search=La+tuya+descargar+empecipiar%C3%A1+automaticament.&string=175548
