### ISSUE TITLE
Unclosed strong tag and em tag in sq locale

### ISSUE THREAD

**Issue by pdehaan** [mozilla-l10n/www.mozilla.org#314]
https://github.com/mozilla-l10n/www.mozilla.org/blob/822c0b778ba73aa4aa609916feddde75636e04fb/sq/firefox/new/trailhead.lang#L77-L78

https://github.com/mozilla-l10n/www.mozilla.org/blob/822c0b778ba73aa4aa609916feddde75636e04fb/sq/mozorg/internet-health/privacy-security.lang#L250-L251

Looks like the first result has a closing `</ strong>` tag (with space), and the second result has an invalid `<em>hacking</a>` tag combo (guessing the `</a>` should be a `</em>`).

Also interesting is that on the privacy-security.lang result, I don't see the source `<em>` tag in the original en-US string, so maybe we can remove the emphasis completely. 🤷‍♂ 

```sh
$ npx pdehaan/lang-html-lint './sq/**/*.lang'

[
  {
    "file": "./sq/firefox/new/trailhead.lang",
    "errors": [
      {
        "column": 1,
        "code": "E042",
        "data": {},
        "rule": "tag-close",
        "file": "./sq/firefox/new/trailhead.lang",
        "html": "<strong> Shfletimi Privat </ strong> pastron historinë tuaj për ta mbajtur atë të fshehtë nga çdokush që përdor kompjuterin tuaj.",
        "index": 1
      }
    ]
  },
  {
    "file": "./sq/mozorg/internet-health/privacy-security.lang",
    "errors": [
      {
        "column": 127,
        "code": "E042",
        "data": {},
        "rule": "tag-close",
        "file": "./sq/mozorg/internet-health/privacy-security.lang",
        "html": "Organizim të përbashkët <a href=\"%(standford)s\" rel=\"external\">bisedash me Stanford’s Center for Internet and Society</a> mbi <em>hacking</a> nga qeveria.",
        "index": 1
      }
    ]
  }
]
```

**Comment by peiying2** [comment]
Fixed.
