### ISSUE TITLE
firefox/new/trailhead.lang: tag join_firefox_072019 is not correct at string level

### ISSUE THREAD

**Issue by peiying2** [mozilla-l10n/www.mozilla.org#323]
Didn't spot the mismatch between the strings with tags and the tag on the top of the page.

https://github.com/mozilla-l10n/bedrock-l10n/blob/36bc69cede301a5518741ba45d14e19ddaf21b79/en-US/firefox/new/trailhead.lang#L1

https://github.com/mozilla-l10n/bedrock-l10n/blob/36bc69cede301a5518741ba45d14e19ddaf21b79/en-US/firefox/new/trailhead.lang#L114. All new strings have the same issue. 

@alexgibson,

**Comment by peiying2** [comment]
Fixed.

**Comment by alexgibson** [comment]
@peiying2 thank you for catching the error, and the fix!
